In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
b = np.array([5, 4, 3, 2, 1])
b

array([5, 4, 3, 2, 1])

In [11]:
a + b

array([6, 6, 6, 6, 6])

In [12]:
a ** b

array([ 1, 16, 27, 16,  5])

In [13]:
c = np.array([[1,20,3], [4,5,6]])
c

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [16]:
np.concatenate([a, b], axis=0)

array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

In [17]:
a.shape

(5,)

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a.shape

(2, 3)

In [20]:
a = np.array(0)
a

array(0)

In [21]:
a.shape

()

In [24]:
a = np.array(1)
a.ndim

0

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
a = a.reshape(3, 2)
print(a.shape)

(2, 3)
(3, 2)


In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a = a.reshape(1, 1, 1, 1, 6)

b = np.array([1, 2, 3, 4, 5, 6])
b = b.reshape(1, 1, 1, 1, 6)

a * b

array([[[[[ 1,  4,  9, 16, 25, 36]]]]])

In [39]:
a = np.array([[1, 2, 3, 4]])     # 形状 (1, 3)
b = np.array([[4], [5], [6]]) # 形状 (3, 1)
result = a + b

print(a)
print()
print(b)
print()
print(result)
print()
print(result.shape)

[[1 2 3 4]]

[[4]
 [5]
 [6]]

[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]

(3, 4)


In [44]:
result[:, 0:1]

array([[5],
       [6],
       [7]])

[1, 2, 3]