### Day14: 列表的扩展 - Numpy Array 入门！

Sarah老师好！今天让我们为列表添加一些功能，让它的各种运算变得更方便！

具体要添加什么功能呢？Ken同学在想，要不让列表更像C语言的数组一些吧。我们规定这个列表只能存整数或者浮点数，然后让其支持各种各样的便捷的四则运算之类的。让我来举个例子：

```Python
list1 = MyList([1, 2, 3, 4, 5])
list2 = MyList([5, 4, 3, 2, 1])

# 列表和数字进行四则运算
list1 + 1  # [2, 3, 4, 5, 6]
list1 * 2  # [2, 4, 6, 8, 10]
list1 ** 2  # [1, 4, 9, 16, 25]

# 两个相同length的列表进行四则运算
list1 + list2  # [6, 6, 6, 6, 6]
list1 * list2  # [5, 8, 9, 6, 5]
list1 ** list2  # [1, 16, 27, 16, 5]
```

---

它应该也有一些机制防止违规初始化啥的，而且既然是数组，初始化之后应该就不能改变大小了

```Python
list1 = MyList([1, '1', 1.0])  # 要报错

list1 = MyList([1, 2, 3])
list1.append(4)  # 要报错，因为不能改变大小
```

---

嗯，今天我们就写这么多吧，下面是我打的一些草稿，大部分函数都写好了，剩下一点点等着你来补充

In [8]:
class MyList:
	def __init__(self, _list, dtype=None):
		if not isinstance(_list, list):
			raise TypeError("Input must be a list")
		if dtype is None:
			if not _list:
				raise ValueError("Input list cannot be empty")
			if isinstance(_list[0], int):
				self.dtype = int
			elif isinstance(_list[0], float):
				self.dtype = float
			else:
				raise TypeError("List must contain only integers or floats")
		elif dtype not in ["int", "float"]:
			raise TypeError("dtype must be 'int' or 'float'")
		else:
			self.dtype = dtype
			
		self.__list = []
		for each in _list:
			if isinstance(each, self.dtype):
				self.__list.append(each)
			else:
				raise TypeError("List must contain only integers or floats")
			
		self.len = len(self.__list)

	def __len__(self):
		return self.len

	def __repr__(self):
		return f"MyList({self.__list})"

	def __add__(self, other):
		temp_list = self.__list.copy()
		if isinstance(other, MyList):
			for i in range(len(self.__list)):
				temp_list[i] += other.__list[i]
		else:
			for i in range(len(self.__list)):
				temp_list[i] += other
		return MyList(temp_list)

	def __sub__(self, other):
		temp_list = self.__list.copy()
		if isinstance(other, MyList):
			for i in range(len(self.__list)):
				temp_list[i] -= other.__list[i]
		else:
			for i in range(len(self.__list)):
				temp_list[i] -= other
		return MyList(temp_list)

	def __mul__(self, other):
		temp_list = self.__list.copy()
		if isinstance(other, MyList):
			for i in range(len(self.__list)):
				temp_list[i] *= other.__list[i]
		else:
			for i in range(len(self.__list)):
				temp_list[i] *= other
		return MyList(temp_list)
	
	def __truediv__(self, other):
		temp_list = self.__list.copy()
		if isinstance(other, MyList):
			for i in range(len(self.__list)):
				temp_list[i] /= other.__list[i]
		else:
			for i in range(len(self.__list)):
				temp_list[i] /= other
		return MyList(temp_list)
	
	def __floordiv__(self, other):
		temp_list = self.__list.copy()
		if isinstance(other, MyList):
			for i in range(len(self.__list)):
				temp_list[i] //= other.__list[i]
		else:
			for i in range(len(self.__list)):
				temp_list[i] //= other
		return MyList(temp_list)
	
	def __mod__(self, other):
		temp_list = self.__list.copy()
		if isinstance(other, MyList):
			for i in range(len(self.__list)):
				temp_list[i] %= other.__list[i]
		else:
			for i in range(len(self.__list)):
				temp_list[i] %= other
		return MyList(temp_list)
	
	def __pow__(self, other):
		temp_list = self.__list.copy()
		if isinstance(other, MyList):
			for i in range(len(self.__list)):
				temp_list[i] **= other.__list[i]
		else:
			for i in range(len(self.__list)):
				temp_list[i] **= other
		return MyList(temp_list)

In [9]:
list1 = MyList([1, 2, 3, 4, 5])
list2 = MyList([5, 4, 3, 2, 1])

print(list1 + list2)
print(list1 - list2)
print(list1 * list2)
print(list1 / list2)
print(list1 % list2)
print(list1 ** list2)
print(list1 // list2)

MyList([6, 6, 6, 6, 6])
MyList([-4, -2, 0, 2, 4])
MyList([5, 8, 9, 8, 5])
MyList([0.2, 0.5, 1.0, 2.0, 5.0])
MyList([1, 2, 0, 0, 0])
MyList([1, 16, 27, 16, 5])
MyList([0, 0, 1, 2, 5])


In [10]:
import numpy as np
a = np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [11]:
b = np.array([5, 4, 3, 2, 1])
b

array([5, 4, 3, 2, 1])

In [12]:
a + b


array([6, 6, 6, 6, 6])

In [13]:
a ** b

array([ 1, 16, 27, 16,  5])

In [14]:
np.concatenate(a, b)


TypeError: only integer scalar arrays can be converted to a scalar index

In [6]:
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

In [15]:
a.shape

(5,)

In [24]:
a = np.array([[1,2,3], [4, 5, 6]])
a.ndim
print(a)
print(a.shape)
a = a.reshape(-1,2)
print(a)
print(a.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
